name: mediscan
description: MediScan - Digital Prescription Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  # Essentials only 
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  url_launcher: ^6.2.2
  intl: ^0.20.2
  fluttertoast: ^8.2.2
  permission_handler: ^11.0.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_gen: ^5.10.0
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_localization: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700